- name: Install Apache
  apt:
    name: apache2
    state: latest

- name: Install PHP
  apt:
    name: php
    state: latest

- name: Install libapache2-mod-php
  apt:
    name: libapache2-mod-php
    state: latest

- name: Use app_php file template
  template:
    src: /vagrant/app_php.j2
    dest: /var/www/html/app.php
    owner: root
    group: root
    mode: '0644'
